### PR TITLE
Typo in readme

### PR DESCRIPTION
**Pull request by szepeviktor**
I've started filter and action wiki pages: https://github.com/kasparsd/minit/wiki/Minit-filters
Please correct me.

### CODE REVIEW

**Comment by kasparsd** [comment]
Thank you @szepeviktor! That is a great initiative!

Once we're happy with the Wiki page, I suggest we added that contents to the `readme.md` since it doesn't have anything in the "Description" yet. What do you think?

**Comment by szepeviktor** [comment]
OK.
I would add a WP.org style readme.txt to make it possible to use afragen/github-updater.

**Comment by kasparsd** [comment]
@szepeviktor I would like to keep the markdown version as the canonical readme file so we could use a git hook to automatically produce the WP.org compatible `readme.txt`. I've used the following script https://github.com/kasparsd/wp-deploy/blob/master/deploy.sh#L45-L48

**Comment by szepeviktor** [comment]
We could also add use cases to every hook.

**Pull request merged**
