### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by kasparsd**
Work in progress

### To-do

- [x] Ensure that bumping plugin version will bust the cache

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you for the TOC.

**Comment by markoheijnen** [comment]
Back to the caching again. Currently you have a cache and a file_exists. When the cache expires, the file still will not be generated because of the file_exists on line 139.

Somehow I'm really eager to say ditch the caching. When do we really need to generate it ;)

**Comment by szepeviktor** [comment]
@kasparsd Do you plan to release it with custom `wp-content`location support?

**Comment by szepeviktor** [comment]
@kasparsd Hello! Do you see when this PR may be complete?

**Comment by szepeviktor** [comment]
@kasparsd Thank you for merging.
A to-be-human stays in his mother's womb for 9 months also.

**Comment by kasparsd** [comment]
Haha @szepeviktor, we actually did have a baby girl join our family during this time :)

**Pull request merged**
