### PR TITLE
Revert "Filter local path from URL"

### PR DESCRIPTION
**Pull request by kasparsd**
Reverts kasparsd/minit#95

> PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Minit_Js::get_asset_relative_path() in minit/include/minit-js.php:89

### CODE REVIEW

**Comment by szepeviktor** [comment]
@kasparsd Could you help me what is the problem?

**Comment by szepeviktor** [comment]
Should get_asset_relative_path() be static??

**Comment by kasparsd** [comment]
@szepeviktor No, `minit-js.php` still referenced `get_asset_relative_path()` which was removed.

**Comment by szepeviktor** [comment]
I think I am beginning to get it.
You use `$src` - the local relative path - in `minit_item( $content, $handle, $src )` only for making up absolute URL-s in `resolve_urls` and `resolve_imports`.

I am thinking about changing the third parameter to the **absolute URL** so it better fits its usage.

**Pull request merged**
