### PR TITLE
Rewrite of get_asset_relative_path() to do str_replace instead on several paths

### PR DESCRIPTION
**Pull request by markoheijnen**
Simple str_replace() on the url with paths know seems to work really good. I do hate to use the constants you shouldn't really use.

### CODE REVIEW

**Comment by markoheijnen** [comment]
Well, I broke the minit_item() part. Forgot about the $src being passed without ABSPATH what is currently the full path.

**Comment by szepeviktor** [comment]
@kasparsd Is there a way to merge this one?

**Comment by kasparsd** [comment]
@szepeviktor I feel like this needs some additional testing -- it still relies on `ABSPATH` and `$_SERVER` variables.

**Comment by szepeviktor** [comment]
@kasparsd Could you give me a hint how to move forward with this?
Should I write tests?

**Comment by kasparsd** [comment]
@szepeviktor This pull request does many major changes to be included in one go, I think.

Secondly, I don't think it actually fixes any existing issues (I might be wrong here) so I would like to avoid changing things without any particular reason.

**Comment by szepeviktor** [comment]
@kasparsd I issue I know of is non-standard wp-content location.
All my WP installs use /static instead of /wp-content.
AFAIK Minit is not able to handle that and this PR fixes it.

**Comment by kasparsd** [comment]
Thanks for the confirmation @szepeviktor! Let's fix that in #93.

**Comment by markoheijnen** [comment]
Sadly it's only one change but you are right, the impact is major.

**Pull request closed without merging**
