### PR TITLE
Make WPCS happy and the code more readable

### PR DESCRIPTION
**Pull request by szepeviktor**
Mostly braces for `if`-s and indentations.

### CODE REVIEW

**Comment by kasparsd** [comment]
Thank you @szepeviktor!

**Comment by szepeviktor** [comment]
For the record:
```
phpcbf --standard=PSR2 --sniffs=Generic.ControlStructures.InlineControlStructure,Squiz.WhiteSpace.ScopeClosingBrace .
phpcbf --standard=WordPress-Core .
```

**Comment by kasparsd** [comment]
@szepeviktor We should probably start using https://github.com/xwp/wp-dev-lib

**Comment by szepeviktor** [comment]
Yes, some Travis tests (unit test, functional test, and code styling) would be nice.

**Pull request merged**
